README.md

Looks like something got a little munged, this fixes the url and links for the inline badges so they link to the proper places and display in SVG for Retina/HiDPI displays.

Fix SVG badges in README

---

lib/extwitter/api/streaming.ex

This is a tiny optimization on how CRLFs are checked (`String.ends_with?` is faster than a regex), which speeds up the stream processing process by a few percentage points.
There are of course bigger fish to fry than this… E.g. it shouldn’t make a huge difference but I wanted to do a quick example of the sort of profiling/changes that should be possible since #11 to encourage people to look for optimization opportunities.
Before:
```
#process stream - single chunk:     100000   17.98 µs/op
#process stream - multi chunk:       50000   39.90 µs/op
```
After:
```
#process stream - single chunk:     100000   16.70 µs/op
#process stream - multi chunk:       50000   35.78 µs/op
```

CRLF parsing micro-optimization

---

lib/extwitter/api/friends_and_followers.ex
test/extwitter_test.exs

ExTwitter.follower_ids/2 can now be called with either a screen name, or
a numeric user id, as the first argument. Either way the appropriate id
option will be made and prepended to the options (the second arg, or
default []).

[extwitter-18] Fixes #18 - follower_ids should support query by user_id

---

README.md

The existing documentation creates the following error:
```
You have configured application :ex_twitter in your config/config.exs
but the application is not available.
This usually means one of:
1. You have not added the application as a dependency in a mix.exs file.
2. You are configuring an application that does not really exist.
Please ensure :ex_twitter exists or remove the configuration.
```
This pr fixes the documentation to say 'extwitter' which doesn't error.

fix config declaration in readme

---

.travis.yml

This routes builds to the container based setup, which has a much faster boot time.

Tell Travis that sudo isn't needed

---

fixture/vcr_cassettes/list_direct_messages.json
fixture/vcr_cassettes/show_direct_message.json
lib/extwitter.ex
lib/extwitter/api/direct_messages.ex
lib/extwitter/model.ex
lib/extwitter/parser.ex
test/extwitter_test.exs

I was not able to test this though. When I run tests, I get following error.
```
1) test shows direct message (ExTwitterTest)
test/extwitter_test.exs:101
** (ExVCR.RequestNotMatchError) Request did not match with any one in the current cassette: fixture/vcr_cassettes/show_direct_message.json.
Delete the current cassette with [mix vcr.delete] and re-record.
stacktrace:
lib/exvcr/handler.ex:116: ExVCR.Handler.raise_error_if_cassette_already_exists/1
lib/exvcr/handler.ex:100: ExVCR.Handler.get_response_from_server/2
(inets) :httpc.request(:get, {'https://api.twitter.com/1.1/direct_messages/show/446328507694845952.json?oauth_signature=ZyUwlXCAMj8CXyr2V6kSfHcEOjo%3D&oauth_version=1.0&oauth_nonce=fVfwbwczFr6Lf6h7K9MppaoK%2FpdE7NvZqUUyYjQTM%2Bg%3D&oauth_timestamp=1446520933&oauth_signature_method …
```

Add support to show a single direct message.

---

lib/extwitter.ex
lib/extwitter/api/auth.ex
test/extwitter_test.exs

The oauth_callback parameter should be POSTed to `/oauth/request_token` according to https://dev.twitter.com/web/sign-in/implementing .
This commit
- adds `ExTwitter.request_token(redirect_url)`
- removes `redirect_url` parameter from `ExTwitter.authorize_url`
- removes `redirect_url` parameter from `ExTwitter.authenticate_url`

Fix auth methods so that redirect_url makes sense

---

lib/extwitter/model.ex

The `extended_entities` field is not listed here https://dev.twitter.com/overview/api/tweets but does exist. See also https://dev.twitter.com/overview/api/entities-in-twitter-objects#extended_entities

Add extended_entities field to Model.Tweet

---

mix.exs
mix.lock

This fixes annoying warnings when building under Elixir 1.2.x.
I had to unlock `combine` and `tzdata` as well to satisfy dependency
constraints.
Travis CI says nothing breaks : https://travis-ci.org/jonathanperret/extwitter/builds/105125735

Upgrade timex to 1.0.0

---

lib/extwitter/model.ex
test/extwitter_test.exs

Twitter provides the `user_id` and `screen_name` for the authenticating user in the `oauth/access_token` response. This change makes these values accessible on the AccessToken struct, saving a `/verify_credentials` call to know who just authenticated.

Expose user_id and screen_name from access_token response

---

lib/extwitter/api/base.ex
mix.exs

Drop Timex.Date.now() call in favor of native Erlang

---

fixture/custom_cassettes/failed_connection.json
lib/extwitter/api/base.ex
lib/extwitter/exception.ex
test/extwitter_test.exs

I've added a custom `ConnectionError` exception, to trap situations where the connection to Twitter fails. This is an improvement over what currently happens, which is a `MatchError` exception.

Trap connection errors and raise with custom exception

---

lib/extwitter/model.ex

Twitter now has support for 'extended' tweets, which are longer, etc. [More info here](https://dev.twitter.com/overview/api/upcoming-changes-to-tweets). This adds support for the new fields in the `Tweet` model: `full_text` and `display_text_range`. The streaming API uses another sub element: `extended_tweet`, which I haven't added in this PR.

Add new Tweet fields for extended tweets

---

CHANGELOG.md
lib/extwitter/api/base.ex
lib/extwitter/api/search.ex
lib/extwitter/parser.ex
mix.exs
test/extwitter_test.exs

Return the more-standard elixir tuple of
{:error, message} and let the user decide what
they want to do with it. 
We still raise hard errors for truly unrecoverable
things like missing keys and/or configuration
options.
[Fix #52]

Don’t throw errors for “normal” errors

---

lib/extwitter.ex

The code of `ExTwitter.API.Streaming.stream_filter/2` take timeout value as the second argument.
It must not be a Keyword(e.g `[timeout: 60_000]`).
Instead, It must be a non negative number or `:infinity`.
I thought `timeout` value is passed following codes:
https://github.com/parroty/extwitter/blob/master/lib/extwitter/api/streaming.ex#L25
https://github.com/parroty/extwitter/blob/master/lib/extwitter/api/streaming.ex#L29
https://github.com/parroty/extwitter/blob/master/lib/extwitter/api/streaming.ex#L77
https://github.com/parroty/extwitter/blob/master/lib/extwitter/api/streaming.ex#L80
https://github.com/parroty/extwitter/blob/master/lib/extwitter/api/streaming.ex#L89
https://github.com/parroty/extwitter/blob/master/lib/extwitter/api/streaming.ex#L90 …

Fix document and spec

---

README.md

Avoid missing dependency error on production environments. t.ex: module OAuther is not available

Explicitly specify required libraries

---

lib/extwitter/model.ex

Stream API delivers full tweet text in extended_tweet field. See [here](https://developer.twitter.com/en/docs/tweets/tweet-updates).

Add extended_tweet field to tweet struct

---

lib/extwitter/api/streaming.ex

E.g. in case if `message` is error from `Poison`
```elixir
{{:invalid, "s", 0}, "ss"}
```
сс @parroty

Fixed crash if message is not string actually

---

fixture/vcr_cassettes/lookup_friendship.json
lib/extwitter.ex
lib/extwitter/api/friends_and_followers.ex
lib/extwitter/model.ex
lib/extwitter/parser.ex
test/extwitter_test.exs

This adds support for  https://dev.twitter.com/rest/reference/get/friendships/lookup
- `ExTwitter.friends_lookup(id)`
- `ExTwitter.friends_lookup(id, opts)`

Implement friendships lookup

---

lib/extwitter.ex
lib/extwitter/behaviour.ex

Using a behaviour allows us to mock extwitter with [`mox`](https://github.com/plataformatec/mox). Plus it gives you some nice compiler warnings if things aren't quite right with function definitions.
I've also sorted out some of the types in here
- `Map` -> `map()`
- `Integer` -> `integer()`
- some other modules `Module` that should be `Module.t()` instead

Move all specs into a behaviour file

---

lib/extwitter/model.ex

If you use `extended_mode` for getting tweets the tweet does not have a `text` field, instead it contains a `full_text` field.
ex:
```elixir
ExTwitter.search("search-term", count: 20, tweet_mode: "extended")
```
Reference:
https://developer.twitter.com/en/docs/tweets/tweet-updates

Add `full_text` field back into tweet model

---

README.md

Since Elixir 1.4, it was no longer necessary to add dependencies to the
mix `:applications` list. Elixir figures this out automatically. This
change removes that part from the instructions.

Remove unneeded mix application instructions

---

lib/extwitter/api/auth.ex
lib/extwitter/behaviour.ex
test/extwitter_test.exs

Hi :)
fix auth.ex to cover all patterns and preventing errors
Including this change will give you peace of mind if we get an unintended response :)
For Example
httpc.request may return {:error, hoge}, and down application using extwitter, because you intended only httpc.request return {:ok, hogehoge}
http://erlang.org/doc/man/httpc.html

Covering all patterns and preventing errors

---

README.md

v2 is coming out soon, so we should be explicit as to which API version

Update README to specify Twitter API version

---

mix.exs
mix.lock

Fix for https://github.com/parroty/extwitter/issues/140.

Update oauther for OTP 24 environment

---

lib/extwitter/model.ex

1. Run formatter
2. Since Elixir 1.14 if the `:except` list of `@derive` contains missing fields it raises a compile-time error. `ExTwitter.Model.DirectMessage` does not have a `:raw_data` field, so it should not be present in the `:except` field

Fix derive missing field issue
