- fixture/custom_cassettes/verify_credentials.json
- lib/extwitter.ex
- lib/extwitter/api/users.ex
- test/extwitter_test.exs
> Support account/verify_credentials API

- fixture/vcr_cassettes/destroy_direct_message.json
- fixture/vcr_cassettes/new_direct_message.json
- fixture/vcr_cassettes/sent_direct_messages.json
- lib/extwitter.ex
- lib/extwitter/api/direct_messages.ex
- test/extwitter_test.exs
Add ExTwitter.direct_messages(:sent, options // [])
Add ExTwitter.destroy_direct_message/1 and ExTwitter.destroy_direct_message/2
Add ExTwitter.new_direct_message/2
> Add remaining direct messages API end points

- lib/extwitter/api/streaming.ex
Fixes #31
The solution is twofold:
1) When an `{:error, :socket_closed_remotely}` HTTP message is received, the streaming HTTP process is restarted.
2) When the stream process has its timeout set to `:infinity`, but no messages arrive within a reasonable time (60 seconds), the stream is restarted as well. The rationale behind this is that Twitter sends a newline every 30 seconds as a keepalive message, so we should get something every 30 seconds. (the keepalive is propagated from the HTTP process to the stream process as a `:keepalive` message for this purpose).
> Restart stream when connection closed remotely or no messages sent

- lib/extwitter/api/streaming.ex
Moved setting of `AsyncRequest.processor` filed to stream initialization
> Fix for #12

- fixture/vcr_cassettes/create_favorite_twitter.json
- fixture/vcr_cassettes/destroy_favorite_twitter.json
- lib/extwitter.ex
- lib/extwitter/api/favorites.ex
- test/extwitter_test.exs
Just wired up a couple of simple methods.
> Implement creating/destroying favorites

- lib/extwitter.ex
- lib/extwitter/api/streaming.ex
User stream is needed for listening user mentions/direct messages etc.
Find streaming module didn't have it in, so I did put some basic structure to make it work, didn't create a unit test yet, if anything needed I will add more :)
> added a user streaming

- lib/extwitter.ex
- mix.exs
I was struggling to understand how to make use of the user_stream and why it wasn't doing what I wanted.
I hope this doc addition will be helpful.
> Added helpful doc for user_stream

- README.md
Update deps version to latest one in readme.
Thanks for Extwitter.
> Fix deps version in Readme

- fixture/vcr_cassettes/lookup_users.json
- lib/extwitter.ex
- lib/extwitter/api/users.ex
- lib/extwitter/parser.ex
- run_iex.sh
- test/extwitter_test.exs
Add support for the batched version of users/lookup where one can search for up to 100 users in 1 request.
> Allow for looking up multiple users with a list

- lib/extwitter/api/streaming.ex
Added support for direct messages in streaming API
> Support for direct messages in streaming API

- fixture/vcr_cassettes/blocks.json
- lib/extwitter.ex
- lib/extwitter/api/blocks.ex
- test/extwitter_test.exs
Implemented APIs corresponding to following endpoints:
- [POST blocks/create — Twitter Developers](https://dev.twitter.com/rest/reference/post/blocks/create)
- [POST blocks/destroy — Twitter Developers](https://dev.twitter.com/rest/reference/post/blocks/destroy)
> Implement blocking/unblocking users

- lib/extwitter.ex
- lib/extwitter/api/base.ex
I wrote the code in this pull request to support sending videos, images and gifs using the new beta DM api. I'm leaving out my updated DM code (which supports media and quick replies) as I couldn't get the OAuth working using httpc and added in HTTPoison instead. Let me know if you're interested in the code and I'll create a separate pull request.
> Added media chunk upload functionality

- README.md
See https://github.com/parroty/extwitter/pull/65
> Indicate the usage of Oauther

- lib/extwitter.ex
- lib/extwitter/api/tweets.ex
I wasn't too sure of how to add a test for this, maybe you can provide some assistance?
> Add unretweet function

- lib/extwitter/parser.ex
- test/extwitter_parser_test.exs
> Fix ArgumentError or UnicodeConversionError when parsing request params with a list as value.

- fixture/vcr_cassettes/update_destroy_status_with_chunked_media.json
- fixture/vcr_cassettes/update_destroy_status_with_chunked_media_options.json
- lib/extwitter.ex
- lib/extwitter/api/base.ex
- lib/extwitter/api/tweets.ex
- lib/extwitter/behaviour.ex
- test/extwitter_test.exs
Adds support for creating a tweet with chunked media upload.
> Add support for update with chunked media upload

- lib/extwitter/model.ex
- lib/extwitter/parser.ex
This involves:
- addition of raw_data field to most models
- new model types
- typespecs for all of them
- basic docs for all of them
- refactor of parser.ex
- removal of deprecated fields and addition of new ones
Closes #100
> Add raw_data fields and specs to models

- lib/extwitter.ex
- lib/extwitter/api/direct_messages.ex
> [WIP] Fix dms

- lib/extwitter.ex
- lib/extwitter/api/direct_messages.ex
> Revert "[WIP] Fix dms"

- CHANGELOG.md
- README.md
- lib/extwitter/json.ex
- mix.exs
- mix.lock
Related to issue #121 
Pretty straight forward. All tests pass
> Issue #121 Replace JSON library poison with Jason

- lib/extwitter/behaviour.ex
Hi :)
I found wrong behaviour on access_token/2, so fix it.
> fix some behaviour

- lib/extwitter/api/auth.ex
- lib/extwitter/behaviour.ex
- test/extwitter_test.exs
> Revert "Covering all patterns and preventing errors"

- fixture/vcr_cassettes/destroy_list.json
- lib/extwitter.ex
- lib/extwitter/api/lists.ex
- test/extwitter_test.exs
Sorry to keep doing this one method at a time... I've been making something and building as I go along...
> implement destroying a list

- fixture/vcr_cassettes/add_members_to_list.json
- fixture/vcr_cassettes/destroy_list.json
- lib/extwitter.ex
- lib/extwitter/api/lists.ex
- test/extwitter_test.exs
I'm hoping this is the last one!
> add members to a list

- lib/extwitter/api/base.ex
super small indentation issue here.
> adjust indentation for clarity

- lib/extwitter/api/streaming.ex
- test/extwitter_stream_test.exs
I noticed internal Poison parsing errors while using the streaming API:
```
[error] Error returned, stopping stream ({{:invalid, "{", 8142}, "{\"created_at\":\"Sat Oct 13 23:00:18 +0000 2018\"...
```
Twitter's [API Doc's](https://developer.twitter.com/en/docs/tutorials/consuming-streaming-data.html):
> note that Tweets and other streamed messages will not necessarily fall on HTTP chunk boundaries – be sure to use the delimiter defined above to determine activity boundaries when reassembling the stream.
I took a look into the code and found that sometimes detecting an "end of tweet" was not detecting there was actually two (or more) tweet JSON documents concatenated together. It looks as though each HTTP Chunk returned could have multiple tweets in it.
The line feed (`\r\n`) is always to …
> Allow for multiple tweets in a given message 

- mix.exs
- mix.lock
This pull request includes changes to the `mix.exs` file to update dependencies and improve the application's configuration. The most important changes include adding a new dependency, introducing environment-specific extra applications, and updating the version of an existing dependency.
> chore: Update dependencies and enhance application configuration
